[package]
name = "isup"
version = "0.1.0"
authors = ["Paul Crane <paul@acheronsoft.com>"]

[dependencies]
reqwest = "0.8.8"
serde = "1.0.77"
serde_json = "1.0.27"
serde_derive = "1.0.77"
clap = "2.32.0"
