[package]
name = "isup"
version = "0.1.0"
authors = ["Paul Crane <paul@acheronsoft.com>"]

[dependencies]
reqwest = { git = "https://github.com/seanmonstar/reqwest" }
serde = "1.0.77"
serde_json = "1.0.27"
serde_derive = "1.0.77"
clap = "2.32.0"
failure = "0.1.2"
